import { DoughItem } from "./types";

export const CURATED_DOUGHS: DoughItem[] = [
  // ================= HARD (식사빵류) =================
  {
    id: "g-002",
    name: "아티장 프렌치 바게트 (1box / 20ea)",
    masterName: "🇫🇷 [파리] B 블랑제리",
    region: "파리",
    price: 42000,
    description: "르방 천연효모로 저온 장기 발효한 정통 파리지앵 바게트 생지입니다. 하드계열 빵의 깊은 누룽지향 구수함과 거친 호피무늬 크러스트를 선사합니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "3012345678901",
    category: "global",
    subCategory: "hard",
    imageLabel: "🥖 프렌치 바게트 쿠프 라인",
    iconBg: "bg-yellow-50 text-yellow-850",
    settings: {
      defrostTemp: 24,
      defrostTime: 20,
      fermentTemp: 26,
      fermentHumidity: 85,
      fermentTime: 120,
      bakeTemp: 230,
      bakeTime: 22,
      steam: true,
    },
  },
  {
    id: "h-001",
    name: "천연 효모 호밀 시골 깜빠뉴 (1box / 15ea)",
    masterName: "서울 - 박준현 명장",
    region: "서울",
    price: 48000,
    description: "국산 호밀 30% 배합에 천연 효모종(르뱅)을 더해 구수한 풍미와 쫄깃한 식감이 일품인 클래식 유럽식 깜빠뉴입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "8809123451201",
    category: "master",
    subCategory: "hard",
    imageLabel: "🌾 저온숙성 시골 깜빠뉴",
    iconBg: "bg-stone-100 text-stone-800",
    settings: {
      defrostTemp: 23,
      defrostTime: 35,
      fermentTemp: 27,
      fermentHumidity: 80,
      fermentTime: 100,
      bakeTemp: 220,
      bakeTime: 25,
      steam: true,
    },
  },
  {
    id: "h-002",
    name: "정통 시그니처 사워도우 (1box / 12ea)",
    masterName: "부산 - 김대한 명장",
    region: "부산",
    price: 52000,
    description: "자체 배양산 이스트 프리 미생물 사워 유산균으로 72시간 콜드 세팅 저온 발효한 시큼한 풍미와 깊은 바삭함의 정통 사워도우 생지입니다.",
    stockStatus: "low",
    statusText: "잔여 수량 5 Box",
    barcode: "8809123451202",
    category: "master",
    subCategory: "hard",
    imageLabel: "🌾 천연발효 크러스트 사워도우",
    iconBg: "bg-amber-50 text-amber-900",
    settings: {
      defrostTemp: 24,
      defrostTime: 40,
      fermentTemp: 25,
      fermentHumidity: 78,
      fermentTime: 110,
      bakeTemp: 225,
      bakeTime: 28,
      steam: true,
    },
  },
  {
    id: "h-003",
    name: "샌프란시스코 클래식 바타르 (1box / 18ea)",
    masterName: "🇺🇸 [샌프란시스코] S 베이커리",
    region: "뉴욕",
    price: 50000,
    description: "골든게이트 해풍의 발효 풍미를 재현한 바타르 품목입니다. 바게트보다 단단하고 깜빠뉴보다 속살이 엄청나게 부드러워 브런치 베이스로 추천합니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "1012345678901",
    category: "global",
    subCategory: "hard",
    imageLabel: "🥖 시그니처 샌프란시스코 바타르",
    iconBg: "bg-orange-50 text-orange-950",
    settings: {
      defrostTemp: 23,
      defrostTime: 30,
      fermentTemp: 26,
      fermentHumidity: 82,
      fermentTime: 95,
      bakeTemp: 215,
      bakeTime: 24,
      steam: true,
    },
  },
  {
    id: "h-004",
    name: "엑스트라 버진 촉촉 치아바타 (1box / 25ea)",
    masterName: "🇮🇹 [로마] R 브레드연구소",
    region: "파리",
    price: 44000,
    description: "고품질 이탈리아산 엑스트라 버진 올리브유와 밀가루를 황금비로 가공해 수분율 82%를 극대화한 보들보들하고 쫀득한 샌드위치 최적화 치아바타입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "3912345678902",
    category: "global",
    subCategory: "hard",
    imageLabel: "🍞 올리브 촉촉 치아바타 단면",
    iconBg: "bg-emerald-50 text-emerald-950",
    settings: {
      defrostTemp: 22,
      defrostTime: 25,
      fermentTemp: 29,
      fermentHumidity: 80,
      fermentTime: 70,
      bakeTemp: 210,
      bakeTime: 16,
      steam: true,
    },
  },
  {
    id: "h-005",
    name: "블랙 올리브 로즈마리 포카치아 (1box / 20ea)",
    masterName: "🇮🇹 [밀라노] M 아카데미",
    region: "파리",
    price: 46000,
    description: "생 로즈마리 허브와 블랙 올리브 토핑을 도우 전면에 풍성하게 압착해, 오븐 열기가 닿는 순간 은은한 지중해의 허브향을 뿜어내는 포카치아 생지입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "3912345678903",
    category: "global",
    subCategory: "hard",
    imageLabel: "🍕 지중해 허브 포카치아",
    iconBg: "bg-green-50 text-green-950",
    settings: {
      defrostTemp: 22,
      defrostTime: 20,
      fermentTemp: 30,
      fermentHumidity: 85,
      fermentTime: 65,
      bakeTemp: 200,
      bakeTime: 18,
      steam: false,
    },
  },
  {
    id: "h-006",
    name: "베이킹 명인 호밀 베이글 (1box / 30ea)",
    masterName: "전주 - 이영철 명장",
    region: "전주",
    price: 49000,
    description: "한번 끓는 물에 데쳐 구워낸 정통 유대인 방식에 이영철 명장만의 비법 저온 건식 발효를 연계해 끈적이지 않는 담백 깔끔한 쫄깃함의 최상을 구현했습니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "8809123451203",
    category: "master",
    subCategory: "hard",
    imageLabel: "🥯 명인 호밀 베이글 오가닉",
    iconBg: "bg-stone-50 text-stone-900",
    settings: {
      defrostTemp: 21,
      defrostTime: 15,
      fermentTemp: 28,
      fermentHumidity: 75,
      fermentTime: 45,
      bakeTemp: 195,
      bakeTime: 14,
      steam: true,
    },
  },
  {
    id: "h-007",
    name: "정통 바이에른 브라운 프레첼 (1box / 25ea)",
    masterName: "🇩🇪 [뮌헨] M 베이커리",
    region: "파리",
    price: 47000,
    description: "독일 바이에른 지방의 비법 가성소다 전처리 공정을 거쳐 반들반들한 구릿빛 크러스트 표면과 굵은 천일염 하이라이트가 올려져 씹을수록 구수하고 짭조름합니다.",
    stockStatus: "out",
    statusText: "독일 현지 항공 입고 중",
    barcode: "4012345678901",
    category: "global",
    subCategory: "hard",
    imageLabel: "🥨 바이에른 브라운 프레첼 소금",
    iconBg: "bg-amber-100 text-amber-950",
    settings: {
      defrostTemp: 22,
      defrostTime: 15,
      fermentTemp: 26,
      fermentHumidity: 70,
      fermentTime: 30,
      bakeTemp: 190,
      bakeTime: 15,
      steam: false,
    },
  },
  {
    id: "h-008",
    name: "고소한 현미 무가당 샌드위치 빵 (1box / 20ea)",
    masterName: "서울 - 박준현 명장",
    region: "서울",
    price: 43000,
    description: "설탕과 버터를 첨가하지 않고 국내산 구운 현미 분말과 오트밀을 아낌없이 가미하여 최고의 식단 관리와 담백한 밥빵을 찾으시는 고객을 위한 건강빵입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "8809123451204",
    category: "master",
    subCategory: "hard",
    imageLabel: "🍞 현미 오가닉 건강 바게트식빵",
    iconBg: "bg-amber-50 text-amber-800",
    settings: {
      defrostTemp: 23,
      defrostTime: 25,
      fermentTemp: 28,
      fermentHumidity: 80,
      fermentTime: 80,
      bakeTemp: 200,
      bakeTime: 20,
      steam: true,
    },
  },
  {
    id: "h-009",
    name: "와인무화과 피칸 호밀 브레드 (1box / 15ea)",
    masterName: "부산 - 김대한 명장",
    region: "부산",
    price: 55000,
    description: "고급 레드와인에 깊게 졸인 반건조 달콤 무화과와 바삭하게 구운 피칸 분태를 통호밀 반죽 사이사이 아낌없이 구겨 넣어 무한한 부드러움을 내포한 하드 브레드입니다.",
    stockStatus: "low",
    statusText: "잔여 수량 8 Box",
    barcode: "8809123451205",
    category: "master",
    subCategory: "hard",
    imageLabel: "🍇 무화과 피칸 호밀 가득 단면",
    iconBg: "bg-red-50 text-red-950",
    settings: {
      defrostTemp: 24,
      defrostTime: 35,
      fermentTemp: 27,
      fermentHumidity: 82,
      fermentTime: 90,
      bakeTemp: 210,
      bakeTime: 25,
      steam: true,
    },
  },

  // ================= PASTRY (페이스트리) =================
  {
    id: "m-001",
    name: "오리지널 프랑스 버터 크루아상 (1box / 50ea)",
    masterName: "부산 - 김대한 명장",
    region: "부산",
    price: 68000,
    description: "엄선된 프랑스산 엘르앤비르 AOP 고메버터를 극대화된 레이어로 겹친 초격차 크루아상 생지입니다. 풍부한 버터 오버런과 격의 다른 벌집 구조를 구현합니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "8809123451101",
    category: "master",
    subCategory: "pastry",
    imageLabel: "🥐 크루아상 고해상도 단면",
    iconBg: "bg-amber-100 text-amber-800",
    settings: {
      defrostTemp: 22,
      defrostTime: 30,
      fermentTemp: 28,
      fermentHumidity: 80,
      fermentTime: 90,
      bakeTemp: 175,
      bakeTime: 15,
      steam: true,
    },
  },
  {
    id: "m-002",
    name: "시그니처 수제 애플파이 (1box / 30ea)",
    masterName: "서울 - 박준현 명장",
    region: "서울",
    price: 45000,
    description: "아부지가 가꾸신 영주 사과를 직접 졸여 졸여내어 지나치지 않은 깔끔한 산미의 수제 필링과 바삭하게 결 부서지는 퍼프 페이스트리 시트의 최상의 밸런스입니다.",
    stockStatus: "low",
    statusText: "잔여 수량 10 Box",
    barcode: "8809123451102",
    category: "master",
    subCategory: "pastry",
    imageLabel: "🍎 애플파이 황금빛 텍스처",
    iconBg: "bg-red-50 text-red-800",
    settings: {
      defrostTemp: 20,
      defrostTime: 20,
      fermentTemp: 29,
      fermentHumidity: 75,
      fermentTime: 45,
      bakeTemp: 190,
      bakeTime: 18,
      steam: false,
    },
  },
  {
    id: "m-003",
    name: "카카오 72% 리얼 뺑오쇼콜라 (1box / 40ea)",
    masterName: "전주 - 이영철 명장",
    region: "전주",
    price: 72000,
    description: "벨기에산 카카오 72% 발로나 초콜릿 바를 2개씩 곧게 지탱하는 프렌치 페이스트리입니다. 쌉싸름함과 진한 카카오 아로마가 아침 기분을 고조시킵니다.",
    stockStatus: "out",
    statusText: "현재 반죽 숙성 중 (품절)",
    barcode: "8809123451103",
    category: "master",
    subCategory: "pastry",
    imageLabel: "🍫 뺑오쇼콜라 리얼 단면",
    iconBg: "bg-stone-100 text-stone-800",
    settings: {
      defrostTemp: 22,
      defrostTime: 25,
      fermentTemp: 28,
      fermentHumidity: 82,
      fermentTime: 80,
      bakeTemp: 180,
      bakeTime: 16,
      steam: true,
    },
  },
  {
    id: "p-001",
    name: "발로나 더티 초코 크러쉬 페이스트리 (1box / 30ea)",
    masterName: "서울 - 박준현 명장",
    region: "서울",
    price: 58000,
    description: "진하게 어우러진 발로나 가나슈 코코아 페이스트와 겹겹이 스며든 헤이즐넛 크림의 미친 조화. 초코 매니아층을 저격할 독보적 극강의 바삭함입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "8809123451301",
    category: "master",
    subCategory: "pastry",
    imageLabel: "🍫 발로나 가나슈 페이스트리",
    iconBg: "bg-amber-950 text-white",
    settings: {
      defrostTemp: 20,
      defrostTime: 30,
      fermentTemp: 27,
      fermentHumidity: 78,
      fermentTime: 85,
      bakeTemp: 175,
      bakeTime: 18,
      steam: false,
    },
  },
  {
    id: "p-002",
    name: "프랑스 카라멜 아몬드 몽블랑 (1box / 20ea)",
    masterName: "🇫🇷 [파리] P 파티세리",
    region: "파리",
    price: 64000,
    description: "돌돌 수십 줄 감겨 올라간 원통 기둥형 페이스트리에 프랑스 카라멜 가나슈 시럽을 흠뻑 터치하여, 겉은 바싹하고 속살은 아기 뺨처럼 부드러운 몽블랑입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "3012345678902",
    category: "global",
    subCategory: "pastry",
    imageLabel: "🧁 아몬드 카라멜 데들리 몽블랑",
    iconBg: "bg-amber-50 text-amber-950",
    settings: {
      defrostTemp: 22,
      defrostTime: 35,
      fermentTemp: 28,
      fermentHumidity: 80,
      fermentTime: 90,
      bakeTemp: 180,
      bakeTime: 20,
      steam: false,
    },
  },
  {
    id: "p-003",
    name: "달콤 알싸 갈릭 어니언 데니쉬 (1box / 30ea)",
    masterName: "부산 - 김대한 명장",
    region: "부산",
    price: 51000,
    description: "국산 의성 마늘 분태와 대파 어니언 크림을 데니쉬 생지 포켓에 가득 얹어, 구워지는 순간 고소하고 달큰한 깊은 생마늘 아로마가 온 주방을 자극합니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "8809123451302",
    category: "master",
    subCategory: "pastry",
    imageLabel: "🧄 의성 마늘갈릭 벌집 데니쉬",
    iconBg: "bg-yellow-50 text-yellow-900",
    settings: {
      defrostTemp: 21,
      defrostTime: 20,
      fermentTemp: 29,
      fermentHumidity: 75,
      fermentTime: 50,
      bakeTemp: 185,
      bakeTime: 15,
      steam: false,
    },
  },
  {
    id: "p-004",
    name: "미니 고메 한입 버터 크루아상 (1box / 80ea)",
    masterName: "🇫🇷 [파리] C 불랑제리",
    region: "파리",
    price: 59000,
    description: "프랑스 본토 미니어처 가공 표준에 맞추어 단 한입 크기에 정밀 버터 레이어 설계를 밀집 투영한 커피 곁들임 한입 디저트 전용 미니 크루아상 생지입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "3012345678903",
    category: "global",
    subCategory: "pastry",
    imageLabel: "🥐 프랑스 프리미엄 미니 크루아상",
    iconBg: "bg-yellow-50 text-yellow-805",
    settings: {
      defrostTemp: 22,
      defrostTime: 20,
      fermentTemp: 28,
      fermentHumidity: 82,
      fermentTime: 65,
      bakeTemp: 175,
      bakeTime: 12,
      steam: true,
    },
  },
  {
    id: "p-005",
    name: "크로플 전용 고밀도 크루아상 생지 (1box / 45ea)",
    masterName: "전주 - 이영철 명장",
    region: "전주",
    price: 61000,
    description: "와플 팬 프레스기의 강한 고온 압축률 속성에서도 촉촉성이 증발하여 타는 것을 방지하기 위해 가습 배율을 5% 정밀 보강한 크로플 최적화 생지입니다.",
    stockStatus: "low",
    statusText: "잔여 수량 14 Box",
    barcode: "8809123451303",
    category: "master",
    subCategory: "pastry",
    imageLabel: "🧇 고밀도 압축용 벌집 크로플",
    iconBg: "bg-orange-50 text-orange-800",
    settings: {
      defrostTemp: 22,
      defrostTime: 25,
      fermentTemp: 27,
      fermentHumidity: 85,
      fermentTime: 70,
      bakeTemp: 170,
      bakeTime: 10,
      steam: false,
    },
  },
  {
    id: "p-006",
    name: "바닐라빈 커스터드 과일 데니쉬 (1box / 25ea)",
    masterName: "🇯🇵 [도쿄] A 베이커리",
    region: "도쿄",
    price: 52000,
    description: "마다가스카르산 천연 바닐라 캐비어 빈을 빽빽하게 타작한 커스터드 크림이 데니쉬 페이스트리 코어에 충진되어 오븐에서 농가 구워지는 달콤 디저트입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "4901234567902",
    category: "global",
    subCategory: "pastry",
    imageLabel: "🍈 도쿄 천연 바닐라과일 데니쉬",
    iconBg: "bg-emerald-50 text-emerald-900",
    settings: {
      defrostTemp: 20,
      defrostTime: 20,
      fermentTemp: 28,
      fermentHumidity: 78,
      fermentTime: 60,
      bakeTemp: 180,
      bakeTime: 16,
      steam: false,
    },
  },
  {
    id: "p-007",
    name: "시나몬 브라운슈가 스월 데니쉬 (1box / 30ea)",
    masterName: "서울 - 박준현 명장",
    region: "서울",
    price: 49000,
    description: "부드러운 데니쉬 시트에 메이플 시럽과 브라운 슈가, 알싸한 최고급 실론 계피 가루를 소용돌이 모양으로 돌려 감아 향긋한 조화를 추구하는 정통 디저트입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "8809123451304",
    category: "master",
    subCategory: "pastry",
    imageLabel: "🧁 시나몬 계피 오성 소용돌이",
    iconBg: "bg-stone-100 text-stone-900",
    settings: {
      defrostTemp: 21,
      defrostTime: 25,
      fermentTemp: 28,
      fermentHumidity: 80,
      fermentTime: 80,
      bakeTemp: 175,
      bakeTime: 18,
      steam: false,
    },
  },

  // ================= SOFT (소프트/간식) =================
  {
    id: "g-001",
    name: "오리지널 긴자 메론빵 (1box / 40ea)",
    masterName: "🇯🇵 [도쿄] A 베이커리",
    region: "도쿄",
    price: 58000,
    description: "도쿄 긴자 본점의 비법 쿠키 반죽과 촉촉한 바닐라빈 커스터드 필링을 적용했습니다. 겉은 와그작 씹히는 설탕 결정, 속은 깃털처럼 가볍고 부드러운 수분감을 가집니다.",
    stockStatus: "in",
    statusText: "국내 물류센터 출고 대기",
    barcode: "4901234567891",
    category: "global",
    subCategory: "soft",
    imageLabel: "🍈 긴자 메론빵 시그니처 비주얼",
    iconBg: "bg-emerald-50 text-emerald-800",
    settings: {
      defrostTemp: 20,
      defrostTime: 15,
      fermentTemp: 30,
      fermentHumidity: 70,
      fermentTime: 50,
      bakeTemp: 170,
      bakeTime: 12,
      steam: false,
    },
  },
  {
    id: "s-001",
    name: "신안 천일염 버터 소금빵 (1box / 40ea)",
    masterName: "부산 - 김대한 명장",
    region: "부산",
    price: 60000,
    description: "전라도 신안에서 공수한 프리미엄 천일염 토핑과 가성비 최고의 고메 엘르앤비르 롤 버터가 빵 안쪽 동굴에 가득 녹아내려 자박하게 기름진 소금빵입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "8809123451401",
    category: "master",
    subCategory: "soft",
    imageLabel: "🧈 신안 천일염 황금 동굴 소금빵",
    iconBg: "bg-amber-50 text-amber-900",
    settings: {
      defrostTemp: 22,
      defrostTime: 20,
      fermentTemp: 29,
      fermentHumidity: 82,
      fermentTime: 60,
      bakeTemp: 190,
      bakeTime: 14,
      steam: true,
    },
  },
  {
    id: "s-002",
    name: "대관령 카스텔라 우유 샌드식빵 (1box / 12ea)",
    masterName: "서울 - 박준현 명장",
    region: "서울",
    price: 46000,
    description: "물 한 방울 쓰지 않고 강원도 대관령 유기농 원유 시럽으로 찰기를 높인 촉촉 구수한 식빵 결을 보증합니다. 샌드위치나 토스트 어느 용도로도 최고입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "8809123451402",
    category: "master",
    subCategory: "soft",
    imageLabel: "🍞 대관령 우유 100% 식빵",
    iconBg: "bg-stone-50 text-stone-850",
    settings: {
      defrostTemp: 24,
      defrostTime: 30,
      fermentTemp: 31,
      fermentHumidity: 85,
      fermentTime: 90,
      bakeTemp: 165,
      bakeTime: 25,
      steam: false,
    },
  },
  {
    id: "s-003",
    name: "대부도 알밤 가득 큐브 밤식빵 (1box / 15ea)",
    masterName: "전주 - 이영철 명장",
    region: "전주",
    price: 49000,
    description: "국내산 대부도 햇밤을 설탕에 지극한 정성으로 당절임해 통째로 밤알갱이를 반죽 안에 메워 넣은, 머리 끝에 소보로 비스킷을 얹은 달콤 큐브 식빵 생지입니다.",
    stockStatus: "low",
    statusText: "잔여 수량 3 Box",
    barcode: "8809123451403",
    category: "master",
    subCategory: "soft",
    imageLabel: "🍞 왕알밤 가득 오성 밤식빵",
    iconBg: "bg-yellow-50 text-yellow-950",
    settings: {
      defrostTemp: 23,
      defrostTime: 25,
      fermentTemp: 30,
      fermentHumidity: 80,
      fermentTime: 80,
      bakeTemp: 170,
      bakeTime: 22,
      steam: false,
    },
  },
  {
    id: "s-004",
    name: "전통 72시간 백년 비법 탕종식빵 (1box / 12ea)",
    masterName: "서울 - 박준현 명장",
    region: "서울",
    price: 48000,
    description: "익반죽(탕종) 기법을 정밀 적용해 수분 분자가 쉽게 마르지 않아, 구운 지 3일이 지나도 갓 구운 오븐 빵처럼 극한의 쫄깃쫄깃함과 부드러움을 간직합니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "8809123451404",
    category: "master",
    subCategory: "soft",
    imageLabel: "🍞 탕종 비법 고수분 쫄깃식빵",
    iconBg: "bg-slate-50 text-slate-900",
    settings: {
      defrostTemp: 24,
      defrostTime: 35,
      fermentTemp: 30,
      fermentHumidity: 84,
      fermentTime: 85,
      bakeTemp: 160,
      bakeTime: 28,
      steam: false,
    },
  },
  {
    id: "s-005",
    name: "달콤 가평 꿀 통단팥 단팥빵 (1box / 40ea)",
    masterName: "부산 - 김대한 명장",
    region: "부산",
    price: 54000,
    description: "충남 부사산 국산 적두 팥알을 명장 고유 불솥에서 장기 조림하고 가평 벌꿀을 코팅하여 알갱이가 온전히 으깨져 씹히는 고풍스러운 부귀 영양 단팥빵입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "8809123451405",
    category: "master",
    subCategory: "soft",
    imageLabel: "🥯 통밤 벌꿀 통단팥 단팥빵",
    iconBg: "bg-red-50 text-red-900",
    settings: {
      defrostTemp: 21,
      defrostTime: 15,
      fermentTemp: 31,
      fermentHumidity: 78,
      fermentTime: 55,
      bakeTemp: 180,
      bakeTime: 13,
      steam: false,
    },
  },
  {
    id: "s-006",
    name: "추억의 바삭 고소 시그니처 소보로 (1box / 40ea)",
    masterName: "전주 - 이영철 명장",
    region: "전주",
    price: 52000,
    description: "땅콩 버터와 특유의 비스킷 크럼블 비율을 획기적으로 조밀 밀집시켜 한 면 전체가 바싹하고 무수한 단맛과 땅콩의 고소함을 뱉어내는 튀김소보로풍 생지입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "8809123451406",
    category: "master",
    subCategory: "soft",
    imageLabel: "🥯 피넛버터 크럼블 소보로",
    iconBg: "bg-amber-55 text-amber-950",
    settings: {
      defrostTemp: 21,
      defrostTime: 15,
      fermentTemp: 30,
      fermentHumidity: 75,
      fermentTime: 50,
      bakeTemp: 180,
      bakeTime: 12,
      steam: false,
    },
  },
  {
    id: "s-007",
    name: "목장 바닐라 커스터드 크림빵 (1box / 40ea)",
    masterName: "서울 - 박준현 명장",
    region: "서울",
    price: 51000,
    description: "생 노른자와 연유 우유, 마다가스카르 바닐라 시럽 커스터드가 부드러운 순백 소프트 빵 안에 완전 밀봉되어 오븐 사워 열기가 닿을 때 폭신하게 가열 배출됩니다.",
    stockStatus: "low",
    statusText: "잔여 수량 6 Box",
    barcode: "8809123451407",
    category: "master",
    subCategory: "soft",
    imageLabel: "🥯 갓 짜낸 프리미엄 슈크림빵",
    iconBg: "bg-yellow-50/70 text-yellow-950",
    settings: {
      defrostTemp: 20,
      defrostTime: 15,
      fermentTemp: 31,
      fermentHumidity: 75,
      fermentTime: 45,
      bakeTemp: 175,
      bakeTime: 11,
      steam: false,
    },
  },
  {
    id: "s-008",
    name: "그릴 킹 롱 소시지 낙엽조리빵 (1box / 25ea)",
    masterName: "🇯🇵 [도쿄] A 베이커리",
    region: "도쿄",
    price: 56000,
    description: "두툼한 소 사육 전용 국산 가공 소시지 낙엽 모양 도우 위에 건조 파슬리와 콘마요네즈 시럽, 데리야끼 토마토 소스가 예쁘게 드리워진 베스트셀러 조리빵입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "4901234567903",
    category: "global",
    subCategory: "soft",
    imageLabel: "🌭 소시지 콘마요 야채조리빵",
    iconBg: "bg-red-50 text-red-900",
    settings: {
      defrostTemp: 22,
      defrostTime: 20,
      fermentTemp: 31,
      fermentHumidity: 80,
      fermentTime: 50,
      bakeTemp: 185,
      bakeTime: 15,
      steam: false,
    },
  },
  {
    id: "s-009",
    name: "동해 바다 바삭 명란마요 소금바게트 (1box / 25ea)",
    masterName: "부산 - 김대한 명장",
    region: "부산",
    price: 59000,
    description: "저염 명란젓과 고소한 특제 소박 마요네즈 필링이 바게트 속에 녹아, 바삭하게 구워진 겉 표면과 극도로 짭쪼름한 동해 풍미 감칠맛이 폭발하는 명란 바게트입니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "8809123451408",
    category: "master",
    subCategory: "soft",
    imageLabel: "🥖 어촌 저염명란 보석 바게트",
    iconBg: "bg-red-50 text-red-950",
    settings: {
      defrostTemp: 23,
      defrostTime: 20,
      fermentTemp: 28,
      fermentHumidity: 78,
      fermentTime: 55,
      bakeTemp: 205,
      bakeTime: 14,
      steam: true,
    },
  }
];

export const MAP_PINS_KOREA = [
  { id: "h-001", city: "서울", master: "박준현 명장", top: "23%", left: "36%", active: true },
  { id: "h-006", city: "전주", master: "이영철 명장", top: "55%", left: "38%", active: true },
  { id: "s-001", city: "부산", master: "김대한 명장", top: "75%", left: "76%", active: true },
];

export const MAP_PINS_GLOBAL = [
  { id: "hub", city: "KCT Hub (South Korea)", country: "KR", top: "43%", left: "75%", isHub: true },
  { id: "g-001", city: "도쿄", country: "JP", top: "42%", left: "80%" },
  { id: "china", city: "상하이", country: "CN", top: "45%", left: "71%" },
  { id: "g-002", city: "파리", country: "FR", top: "33%", left: "47%" },
  { id: "us", city: "뉴욕", country: "US", top: "38%", left: "21%" },
  { id: "canada", city: "토론토", country: "CA", top: "32%", left: "19%" },
];
