import { DoughItem } from "./types";

export const CURATED_DOUGHS: DoughItem[] = [
  {
    id: "m-001",
    name: "오리지널 프랑스 버터 크루아상 (1box / 50ea)",
    masterName: "부산 - 김대한 명장",
    region: "부산",
    price: 68000,
    description: "엄선된 프랑스산 엘르앤비르 AOP 고메버터를 극대화된 레이어로 겹친 초격차 크루아상 생지입니다. 풍부한 버터 오버런과 격의 다른 벌집 구조를 구현합니다.",
    stockStatus: "in",
    statusText: "당일 발송 가능",
    barcode: "8809123451101",
    category: "master",
    imageLabel: "🥐 크루아상 고해상도 단면",
    iconBg: "bg-amber-100 text-amber-800",
    settings: {
      defrostTemp: 22,
      defrostTime: 30,
      fermentTemp: 28,
      fermentHumidity: 80,
      fermentTime: 90,
      bakeTemp: 175,
      bakeTime: 15,
      steam: true,
    },
  },
  {
    id: "m-002",
    name: "시그니처 수제 애플파이 (1box / 30ea)",
    masterName: "서울 - 박준현 명장",
    region: "서울",
    price: 45000,
    description: "아부지가 가꾸신 영주 사과를 직접 졸여 졸여내어 지나치지 않은 깔끔한 산미의 수제 필링과 바삭하게 결 부서지는 퍼프 페이스트리 시트의 최상의 밸런스입니다.",
    stockStatus: "low",
    statusText: "잔여 수량 10 Box",
    barcode: "8809123451102",
    category: "master",
    imageLabel: "🍎 애플파이 황금빛 텍스처",
    iconBg: "bg-red-50 text-red-800",
    settings: {
      defrostTemp: 20,
      defrostTime: 20,
      fermentTemp: 29,
      fermentHumidity: 75,
      fermentTime: 45,
      bakeTemp: 190,
      bakeTime: 18,
      steam: false,
    },
  },
  {
    id: "m-003",
    name: "카카오 72% 리얼 뺑오쇼콜라 (1box / 40ea)",
    masterName: "전주 - 이영철 명장",
    region: "전주",
    price: 72000,
    description: "벨기에산 카카오 72% 발로나 초콜릿 바를 2개씩 곧게 지탱하는 프렌치 페이스트리입니다. 쌉싸름함과 진한 카카오 아로마가 아침 기분을 고조시킵니다.",
    stockStatus: "out",
    statusText: "현재 반죽 숙성 중 (품절)",
    barcode: "8809123451103",
    category: "master",
    imageLabel: "🍫 뺑오쇼콜라 리얼 단면",
    iconBg: "bg-stone-100 text-stone-800",
    settings: {
      defrostTemp: 22,
      defrostTime: 25,
      fermentTemp: 28,
      fermentHumidity: 82,
      fermentTime: 80,
      bakeTemp: 180,
      bakeTime: 16,
      steam: true,
    },
  },
  {
    id: "g-001",
    name: "오리지널 긴자 메론빵 (1box / 40ea)",
    masterName: "🇯🇵 [도쿄] A 베이커리",
    region: "도쿄",
    price: 58000,
    description: "도쿄 긴자 본점의 비법 쿠키 반죽과 촉촉한 바닐라빈 커스터드 필링을 적용했습니다. 겉은 와그작 씹히는 설탕 결정, 속은 깃털처럼 가볍고 부드러운 수분감을 가집니다.",
    stockStatus: "in",
    statusText: "국내 물류센터 출고 대기",
    barcode: "4901234567891",
    category: "global",
    imageLabel: "🍈 긴자 메론빵 시그니처 비주얼",
    iconBg: "bg-emerald-50 text-emerald-800",
    settings: {
      defrostTemp: 20,
      defrostTime: 15,
      fermentTemp: 30,
      fermentHumidity: 70,
      fermentTime: 50,
      bakeTemp: 170,
      bakeTime: 12,
      steam: false,
    },
  },
  {
    id: "g-002",
    name: "아티장 프렌치 바게트 (1box / 20ea)",
    masterName: "🇫🇷 [파리] B 블랑제리",
    region: "파리",
    price: 42000,
    description: "르방 천연효모로 저온 장기 발효한 정통 파리지앵 바게트 생지입니다. 하드계열 빵의 깊은 누룽지향 구수함과 거친 호피무늬 크러스트를 선사합니다.",
    stockStatus: "out",
    statusText: "현지 생산 및 항공 운송 중",
    barcode: "3012345678901",
    category: "global",
    imageLabel: "🥖 프렌치 바게트 쿠프 라인",
    iconBg: "bg-yellow-50 text-yellow-800",
    settings: {
      defrostTemp: 24,
      defrostTime: 20,
      fermentTemp: 26,
      fermentHumidity: 85,
      fermentTime: 120,
      bakeTemp: 230,
      bakeTime: 22,
      steam: true,
    },
  },
];

export const MAP_PINS_KOREA = [
  { id: "m-002", city: "서울", master: "박준현 명장", top: "28%", left: "42%", active: true },
  { id: "m-003", city: "전주", master: "이영철 명장", top: "56%", left: "43%", active: true },
  { id: "m-001", city: "부산", master: "김대한 명장", top: "72%", left: "74%", active: true },
  { id: "daegu", city: "대구", master: "영남 테크노 파크 노드", top: "62%", left: "68%", active: false },
  { id: "daejeon", city: "대전", master: "중부 물류 통합 거점", top: "46%", left: "51%", active: false },
  { id: "gwangju", city: "광주", master: "호남 스마트 저장 챔버", top: "68%", left: "38%", active: false },
  { id: "jeju", city: "제주", master: "서귀포 천연 효소 배양소", top: "91%", left: "34%", active: false },
];

export const MAP_PINS_GLOBAL = [
  { id: "hub", city: "KCT Hub (South Korea)", country: "KR", top: "43%", left: "75%", isHub: true },
  { id: "g-001", city: "도쿄", country: "JP", top: "42%", left: "80%" },
  { id: "china", city: "상하이", country: "CN", top: "45%", left: "71%" },
  { id: "g-002", city: "파리", country: "FR", top: "33%", left: "47%" },
  { id: "us", city: "뉴욕", country: "US", top: "38%", left: "21%" },
  { id: "canada", city: "토론토", country: "CA", top: "32%", left: "19%" },
];
